# Generated by Django 4.0.2 on 2022-02-18 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_rename_first_name_cust_tb_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cust_tb',
            old_name='Number',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='cust_tb',
            name='full_name',
        ),
    ]
