# Generated by Django 4.0.2 on 2022-02-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_rename_number_cust_tb_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_tb',
            name='Number',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cust_tb',
            name='first_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cust_tb',
            name='last_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
