# Generated by Django 4.0.2 on 2022-03-02 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_imgage_tb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='imgage_tb',
            new_name='image_tb',
        ),
    ]
