# Generated by Django 4.0.2 on 2022-03-15 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_image_tb_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='fav_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favactor_title', models.CharField(max_length=200)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.cust_tb')),
            ],
        ),
    ]
