# Generated by Django 4.0.2 on 2022-03-15 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_fav_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='luck_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luckyno_title', models.CharField(max_length=200)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.cust_tb')),
            ],
        ),
    ]
